# Generated by Django 5.1.5 on 2025-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblusers',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Interviewer'), (2, 'Candidate')], max_length=255, null=True),
        ),
    ]
