# Generated by Django 5.1.5 on 2025-01-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_tblusers_end_date_alter_tblusers_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblusers',
            old_name='candidate_id',
            new_name='user_type_id',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='interviewer_id',
        ),
    ]
