# Generated by Django 5.1.5 on 2025-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_rename_candidate_id_tblusers_user_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblusers',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Interviewer'), (2, 'Candidate')], max_length=255, null=True),
        ),
    ]
